import 'package:vocabapp/model/lesson.dart';
import 'package:vocabapp/model/level.dart';
import 'package:vocabapp/model/worte.dart';
import 'package:flutter/material.dart';

class Utils {
  static List<Level> getLevels() {
    return [
      Level(
          name: "A1.1",
          lessons: [
            Lesson(
                name: "Begrüssung",
                words: [
                  Word("Hello", "Hallo", "-", "-", "Nou"),
                  Word("Good morning", "Guten Morgen", "-", "-", "Nou"),
                  Word("Good day", "Guten Tag", "-", "-", "Nou"),
                  Word("Good evening", "Guten Abend", "-", "-", "Nou"),
                  Word("Good night", "Gute Nacht", "-", "-", "Nou"),
                  Word("Goodbye", "Auf Wiedersehen", "-", "-", "Nou"),
                  Word("Bye", "Tschüss", "-", "-", "Nou"),
                  Word("My name is", "Mein Name ist", "-", "-", "Nou"),
                  Word("That is", "Das ist", "-", "-", "Nou"),
                  Word("Who", "Wer", "-", "-", "Nou"),
                  Word("How", "Wie", "-", "-", "Nou"),
                  Word("Mrs", "Frau", "die", "Frauen", "Noun"),
                  Word("Mr", "Herr", "der", "Herren", "Noun"),
                  Word("Name", "Name", "der", "Namen", "Noun"),
                  Word("First name", "Vorname", "der", "Vornamen", "Noun"),
                  Word("Surname", "Familienname", "der", "Familiennamen",
                      "Noun"),
                  Word("Alphabet", "Alphabet", "das", "Alphabete", "Noun"),
                  Word("where from", "Woher", "-", "-", "Nou"),
                  Word("Country", "Land", "das", "Länder", "Noun"),
                  Word("Germany", "Deutschland", "-", "-", "Nou"),
                  Word("Austria", "Österreich", "-", "-", "Nou"),
                  Word("Switzerland", "Schweiz", "die", "-", "Noun"),
                  Word("How's it going ?", "Wie geht's ?", "-", "-", "Nou"),
                  Word("to be called", "heißen", "hat", "geheißen", "Verb"),
                  Word("to spell", "buchstabieren", "hat", "buchstabiert",
                      "Verb"),
                  Word("to be", "sein", "bin", "gewesen", "Verb"),
                  Word("to come", "kommen", "ist", "gekommen", "Verb"),
                  Word("very good", "sehr gut", "-", "-", "Ver"),
                  Word("good", "gut", "-", "-", "veb"),
                  Word("not so good", "nicht so gut", "-", "-", "Ver"),
                  Word("also", "auch", "-", "-", "Ver"),
                  Word("thank you", "danke", "-", "-", "ver"),
                  Word("yes", "ja", "-", "-", "Ver"),
                  Word("no", "nein", "-", "-", "Ver"),
                  Word("Very", "sehr", "-", "-", "Veb"),
                  Word("and", "und", "-", "-", "Veb"),
                ],
                lessonColor: Colors.amber),
            Lesson(
                name: "Berufe",
                words: [
                  Word("Employer", "Arbeitgeber", "der",
                      "ArbeitgeberArbeitgeber", "Noun"),
                  Word(
                      "Formation", "Ausbildung", "die", "Ausbildungen", "Noun"),
                  Word("Occupation", "Beruf", "der", "Berufe", "Noun"),
                  Word("College", "Hochschule", "die", "Hochschulen", "Noun"),
                  Word("University", "UniversitÃ¤t", "die", "UniversitÃ¤ten",
                      "Noun"),
                  Word("Job", "Job", "der", "Jobs", "Noun"),
                  Word("lnternship", "Praktikum", "das", "PraktikumPraktika",
                      "Noun"),
                  Word("School", "Schule", "die", "Schulen", "Noun"),
                  Word("Location", "Stelle", "die", "Stellen", "Noun"),
                  Word("Architect", "Architekt", "der", "Architekten", "Noun"),
                  Word("Doctor", "Arzt", "der", "Arzte", "Noun"),
                  Word("Hairdresser", "Friseur", "der", "Friseure", "Noun"),
                  Word("Engineer", "Ingenieur", "der", "Ingenieure", "Noun"),
                  Word("Journalist", "Journalist", "der", "Journalisten",
                      "Noun"),
                  Word("Waiter", "Kellner", "der", "Kellner", "Noun"),
                  Word("Nurse", "Krankenschwester", "die", "Krankenschwestern",
                      "Noun"),
                  Word("Teacher male)", "Lehrer", "der", "Lehrer", "Noun"),
                  Word("Mechatronics technician", "Mechatroniker", "der", "-",
                      " Noun"),
                  Word("Student", "Student", "der", "Studenten", "Noun"),
                  Word("Actor", "Schauspieler", "der", "Schauspieler", "Noun"),
                  Word("Pupil", "SchÃ¼ler", "der", "SchÃ¼ler", "Noun"),
                  Word("Secretary male)", "SekretÃ¤r", "der", "SekretÃ¤re",
                      "Noun"),
                  Word("Salesman", "VerkÃ¤ufer", "der", "VerkÃ¤ufer", "Noun"),
                  Word("to work", "arbeiten", "hat", "gearbeitet", "Verb"),
                  Word("to study", "studieren", "hat", "studiert", "Verb"),
                  Word("Unemployed", "arbeitslos", "-", "-", "erb"),
                ],
                lessonColor: (Colors.amber[300])!),
            Lesson(
                name: "Familie",
                words: [
                  Word("Family", "Familie", "die", "Familien", "Noun"),
                  Word("Father", "Vater", "der", "Vater..", "Noun"),
                  Word("Mother", "Mutter", "die", "Mutter..", "Noun"),
                  Word("Parents", "Eltern", "die", "ElternPl)", "Noun"),
                  Word("Son", "Sohn", "der", "Sohn..e", "Noun"),
                  Word("Dughter", "Tochter", "die", "Tochter..", "Noun"),
                  Word("Grandfather", "GroÃŸvater", "der", "GroÃŸvater..",
                      "Noun"),
                  Word("Grandpa", "Opa", "der", "Opas", "Noun"),
                  Word("Grandmother", "GroÃŸmutter", "die", "GroÃŸmutter..",
                      "Noun"),
                  Word("Grandma", "Oma", "die", "Omas", "Noun"),
                  Word("Grandparents", "GroÃŸeltern", "die", "GroÃŸelternPl)",
                      "Noun"),
                  Word("Granddaughter", "Enkelin", "die", "Enkelinnen", "Noun"),
                  Word("Grandson", "Enkel", "der", "Enkel", "Noun"),
                  Word("Brother", "Bruder", "der", "Bruder..", "Noun"),
                  Word("Sister", "Schwester", "die", "Schwestern", "Noun"),
                  Word("Siblings", "Geschwister", "die", "GeschwisterPl)",
                      "Noun"),
                  Word("Husband", "Ehemann", "der", "Ehemann..er", "Noun"),
                  Word("Wife", "EheFrau", "die", "EheFrauen", "Noun"),
                  Word("Age", "Alter", "das", "Alter", "Noun"),
                  Word("Marital status", "Familienstand", "der",
                      "Familienstand", "Noun"),
                  Word("to live", "leben", "hat", "gelebt", "Verb"),
                  Word("to live alone", "allein leben", "-", "-", "erb"),
                  Word("to live together", "zusammenleben", "-", "-", "Veb"),
                  Word("divorced", "geschieden", "-", "-", "Vrb"),
                  Word("Married", "verheiratet", "-", "-", "Vrb"),
                ],
                lessonColor: Colors.orange),
            Lesson(
                name: "Möbel",
                words: [
                  Word("Furniture", "MÃ¶bel", "die", "MÃ¶belPl.)", "Noun"),
                  Word("Bed.", "Bett", "das", "Betten", "Noun"),
                  Word("Image", "Bild", "das", "Bilder", "Noun"),
                  Word("Lamp", "Lampe", "die", "Lampen", "Noun"),
                  Word("Cabinet", "Schrank", "der", "Schrank..e", "Noun"),
                  Word("Box", "Kasten", "der", "Kasten", "Noun"),
                  Word("Armchair", "Sessel", "der", "Sessel", "Noun"),
                  Word("Sofa", "das", "-s", "dasSofa", "Noun"),
                  Word("Couch", "Couch", "die", "Couche)s/-en", "Noun"),
                  Word("Chair", "stuhl", "der", "-..e", "Verb"),
                  Word("carpet", "Teppich", "der", "Teppiche", "Noun"),
                  Word("Table", "Tisch", "der", "Tische", "Noun"),
                  Word("Euro", "Euro", "der", "Euros", "Noun"),
                  Word("Cent", "Cent", "der", "Cents", "Noun"),
                  Word("Price", "Preis", "der", "Preise", "Noun"),
                  Word("Offer", "Angebot", "das", "Angebote", "Noun"),
                  Word("Help", "Hilfe", "die", "Hilfen", "Noun"),
                  Word("Zimmer", "das", "", "dasRoom", "Noun"),
                  Word("big", "groÃŸ", "-", "-", "erb"),
                  Word("ugly", "hÃ¤sslich", "-", "-", "Ver"),
                  Word("small", "klein", "-", "-", "Vrb"),
                  Word("short", "kurz", "-", "-", "Vrb"),
                  Word("long", "lang", "-", "-", "Vrb"),
                  Word("light", "leicht", "-", "-", "Ver"),
                  Word("modern", "modern", "-", "-", "Veb"),
                  Word("convenient", "praktisch", "-", "-", "Veb"),
                  Word("bad", "schlecht", "-", "-", "Vrb"),
                  Word("nice", "schÃ¶n", "-", "-", "Vrb"),
                  Word("heavy", "schwer", "-", "-", "Veb"),
                  Word("cheap", "gÃ¼nstig", "-", "-", "Vrb"),
                  Word("expensive", "teuer", "-", "-", "Vrb"),
                ],
                lessonColor: (Colors.lime[700])!),
            Lesson(
                name: "Farbe",
                words: [
                  Word("Colour", "Farbe", "die", "Farben", "Noun"),
                  Word("blue", "blau", "*", "*", "Adjective"),
                  Word("brown", "braun", "*", "*", "Adjective"),
                  Word("yellow", "gelb", "*", "*", "Adjective"),
                  Word("green", "grÃ¼n", "*", "*", "Adjective"),
                  Word("orange", "orange", "*", "*", "Adjective"),
                  Word("red", "rot", "*", "*", "Adjective"),
                  Word("black", "schwarz", "*", "*", "Adjective"),
                  Word("white", "weiÃŸ", "*", "*", "Adjective"),
                  Word("Shape", "Form", "die", "Formen", "Noun"),
                  Word("rectangular", "eckig", "*", "*", "Adjective"),
                  Word("light", "leicht", "*", "*", "Adjective"),
                  Word("new", "neu", "*", "*", "Adjective"),
                  Word("round", "rund", "*", "*", "Adjective"),
                  Word("en", "Material", "das", "-", "Material"),
                  Word("Glass", "Glas", "das", "Glas..er", "Noun"),
                  Word("wood", "Holz", "das", "Holz..er", "Noun"),
                  Word("Metal", "Metall", "das", "Metalle", "Noun"),
                  Word("Paper", "Papier", "das", "Papiere", "Noun"),
                  Word("Plastic", "Plastik", "das", "Plastiken", "Noun"),
                  Word("Plastic", "Kunststoff", "der", "Kunststoffe", "Noun"),
                ],
                lessonColor: (Colors.lightGreen[800])!),
            Lesson(
                name: "Gegenstände",
                words: [
                  Word("Pencil", "Bleistift", "der", "Bleistifte", "Noun"),
                  Word("Glasses", "Brille", "die", "Brillen", "Noun"),
                  Word("Book", "Buch", "das", "Buch..er", "Noun"),
                  Word("Lighter", "Feuerzeug", "das", "Feuerzeuge", "Noun"),
                  Word("Bottle", "Flasche", "die", "Flaschen", "Noun"),
                  Word("Camera", "Fotoapparat", "der", "Fotoapparate", "Noun"),
                  Word("Purse", "GeldbÃ¶rse", "die", "GeldbÃ¶rsen", "Noun"),
                  Word("chain", "Kette", "die", "Ketten", "Noun"),
                  Word("ballpoint pen", "Kugelschreiber", "der",
                      "Kugelschreiber", "Noun"),
                  Word(
                      "Umbrella", "Regenschirm", "der", "Regenschirme", "Noun"),
                  Word("Ring", "Ring", "der", "Ringe", "Noun"),
                  Word("Key", "SchlÃ¼ssel", "der", "SchlÃ¼ssel", "Noun"),
                  Word("Soap", "Seife", "die", "Seifen", "Noun"),
                  Word(
                      "Match", "Streichholz", "das", "Streichholz..er", "Noun"),
                  Word("Bag", "Tasche", "die", "Taschen", "Noun"),
                  Word("Watch", "Uhr", "die", "Uhren", "Noun"),
                ],
                lessonColor: (Colors.cyan[800])!),
            Lesson(
                name: "Büro",
                words: [
                  Word("Workplace", "Arbeitsplatz", "der", "Arbeitsplatz..e",
                      "Noun"),
                  Word("Screen", "Bildschirm", "der", "Bildschirme", "Noun"),
                  Word("Stamps", "Briefmarke", "die", "Briefmarken", "Noun"),
                  Word("Office", "BÃ¼ro", "das", "BÃ¼ros", "Noun"),
                  Word("Boss", "Chef", "der", "Chefs", "Noun"),
                  Word("Computer", "Computer", "der", "Computer", "Noun"),
                  Word("Printer", "Drucker", "der", "Drucker", "Noun"),
                  Word("Company", "Firma", "die", "Firmaen", "Noun"),
                  Word("Formular", "Formular", "das", "Formulare", "Noun"),
                  Word("Mobile phone", "Handy", "das", "Handys", "Noun"),
                  Word("Calendar", "Kalender", "der", "Kalender", "Noun"),
                  Word("Laptop", "Laptop", "der", "Laptops", "Noun"),
                  Word("Mouse", "Maus", "die", "Maus..e", "Noun"),
                  Word("Notebook", "Notizbuch", "das", "Notizbuch..er", "Noun"),
                  Word("bill", "Rechnung", "die", "Rechnungen", "Noun"),
                  Word("SMS", "SMS", "die", "SMS", "Noun"),
                  Word("pen", "Stift", "der", "Stifte", "Noun"),
                  Word("Meeting", "Termin", "der", "Termine", "Noun"),
                ],
                lessonColor: (Colors.blue[900])!),
            Lesson(
                name: "Freizeit und Hobbys",
                words: [
                  Word("Excursion", "Ausflug", "der", "Ausfluge", "Noun"),
                  Word("Film", "Film", "der", "Filme", "Noun"),
                  Word("Free time", "Freizeit", "die", "Freizeit", "Noun"),
                  Word("Hobby", "Hobby", "das", "Hobbys", "Noun"),
                  Word("Cinema", "Kino", "das", "Kinos", "Noun"),
                  Word("Music", "Musik", "die", "Musik", "Noun"),
                  Word("Favourite film", "Lieblingsfilm", "der",
                      "Lieblingsfilme", "Noun"),
                  Word("to bake", "backen", "hat", "gebacken", "Verb"),
                  Word("to visit", "besuchen", "hat", "besucht", "Verb"),
                  Word("to meet", "treffen", "hat", "getroffen", "Verb"),
                  Word("to photograph", "fotografieren", "hat", "fotografiert",
                      "Verb"),
                  Word("to cook", "kochen", "hat", "gekocht", "Verb"),
                  Word("to read", "lesen", "hat", "gelesen", "Verb"),
                  Word("to love", "lieben", "hat", "geliebt", "Verb"),
                  Word("to paint", "malen", "hat", "gemalt", "Verb"),
                  Word("to hear music", "Musik hÃ¶ren", "hat", "gehÃ¶rt",
                      "Verb"),
                  Word("to ride a bicycle", "Rad fahren", "ist", "gefahren",
                      "Verb"),
                  Word("to swim", "schwimmen", "ist", "geschwommen", "Verb"),
                  Word("to sing", "singen", "hat", "gesungen", "Verb"),
                  Word("to go for a walk", "Spazieren gehen", "ist", "gegangen",
                      "Verb"),
                  Word("to play", "spielen", "hat", "gespielt", "Verb"),
                  Word("to dance", "tanzen", "hat", "getanzt", "Verb"),
                ],
                lessonColor: (Colors.purple[700])!),
            Lesson(
                name: "In der Stadt",
                words: [
                  Word("Exhibition", "Ausstellung", "die", "-en", "Noun"),
                  Word("", "Bar", "die", "-s", "Bar"),
                  Word("Café", "Café", "das", "-s", "Noun"),
                  Word("Disco", "Disco", "die", "-s", "Noun"),
                  Word("Pub", "Kneipe", "die", "-n", "Noun"),
                  Word("Concert", "Konzert", "das", "-e", "Noun"),
                  Word("Museum", "Museum", "das", "Museen", "Noun"),
                  Word("Restaurant", "Restaurant", "das", "-s", "Noun"),
                  Word("Pool", "Schwimmbad", "das", "-..er", "Noun"),
                  Word("Theatre", "Theater", "das", "-", "Noun"),
                  Word("Tomorrow", "Morgen", "der", "-", "Noun"),
                  Word("Late Morning", "Vormittag", "der", "-e", "Noun"),
                  Word("Noon", "Mittag", "der", "-e", "Noun"),
                  Word("Afternoon", "Nachmittag", "der", "-e", "Noun"),
                  Word("Evening", "Abend", "der", "-e", "Noun"),
                  Word("Night", "Nacht", "die", "-..e", "Noun"),
                  Word("Day", "Tag", "der", "-e", "Noun"),
                  Word("Week", "Woche", "die", "-n", "Noun"),
                  Word("Monday", "Montag", "der", "-e", "Noun"),
                  Word("Tuesday", "Dienstag", "der", "-e", "Noun"),
                  Word("Wednesday", "Mittwoch", "der", "-e", "Noun"),
                  Word("Thursday", "Donnerstag", "der", "-e", "Noun"),
                  Word("Friday", "Freitag", "der", "-e", "Noun"),
                  Word("Saturday", "Samstag", "der", "-e", "Noun"),
                  Word("Sunday", "Sonntag", "der", "-e", "Noun"),
                ],
                lessonColor: (Colors.pink[900])!),
            Lesson(
                name: "Lebensmittel und Essen",
                words: [
                  Word("Apple", "Apfel", "der", "-..", "Noun"),
                  Word("Roast", "Braten", "der", "-", "Noun"),
                  Word("Buns", "Brötchen", "das", "-", "Noun"),
                  Word("Bread", "Brot", "das", "-e", "Noun"),
                  Word("Butter", "Butter", "die", "-", "Noun"),
                  Word("Egg", "Ei", "das", "-er", "Noun"),
                  Word("Ice cream", "Eis", "das", "-", "Noun"),
                  Word("Fish", "Fisch", "der", "-e", "Noun"),
                  Word("meat", "Fleisch", "das", "-", "Noun"),
                  Word("cheese", "Käse", "der", "-", "Noun"),
                  Word("Potato", "Kartoffel", "die", "-n", "Noun"),
                  Word("Cake", "Kuchen", "der", "-", "Noun"),
                  Word("Milk", "Milch", "die", "-", "Noun"),
                  Word("Fruit", "Obst", "das", "-", "Noun"),
                  Word("Orange", "Orange", "die", "-n", "Noun"),
                  Word("Rice", "Reis", "der", "-", "Noun"),
                  Word("Cream", "Sahne", "die", "-", "Noun"),
                  Word("Salad", "Salat", "der", "-e", "Noun"),
                  Word("Ham", "Schinken", "der", "-", "Noun"),
                  Word("Chocolate", "Schokolade", "die", "-n", "Noun"),
                  Word("Soup", "Suppe", "die", "-n", "Noun"),
                  Word("Tea", "Tee", "der", "-s", "Noun"),
                  Word("Tomato", "Tomate", "die", "-n", "Noun"),
                  Word("Sausage", "Wurst", "die", "-e", "Noun"),
                  Word("Lemon", "Zitrone", "die", "-n", "Noun"),
                  Word("Onion", "Zwiebel", "die", "-n", "Noun"),
                  Word("Thirst", "Durst", "der", "-", "Noun"),
                  Word("Breakfast", "Frühstück", "das", "-e", "Noun"),
                  Word("Hunger", "Hunger", "der", "-", "Noun"),
                  Word("Refrigerator", "Kühlschrank", "der", "-..e", "Noun"),
                  Word("to eat", "essen", "hat", "gegessen", "Verb"),
                  Word("to eat breakfast", "frühstücken", "hat", "gefrühstückt",
                      "Verb"),
                  Word("to like", "mägen", "hat", "gemocht", "Verb"),
                  Word("to taste", "schmecken", "hat", "geschmekt", "Verb"),
                  Word("to drink", "trinken", "hat", "getrunken", "Verb"),
                ],
                lessonColor: Colors.pink),
            Lesson(
                name: "Verkehrsmittel und Reisen",
                words: [
                  Word("Train station", "Bahnhof", "der", "-e", "Noun"),
                  Word("Platform", "Bahnsteig", "der", "-e", "Noun"),
                  Word("Bus", "Bus", "der", "-se", "Noun"),
                  Word("Stop", "Haltestelle", "die", "-n", "Noun"),
                  Word("Airport", "Flughafen", "der", "-..", "Noun"),
                  Word("Plane", "Flugzeug", "das", "-e", "Noun"),
                  Word("Luggage", "Gepäck", "das", "-", "Noun"),
                  Word("Track", "Gleis", "das", "-e", "Noun"),
                  Word("Suitcase", "Koffer", "der", "-", "Noun"),
                  Word("Suburban train", "S-Bahn", "die", "-en", "Noun"),
                  Word("Tram", "Straßenbahn", "die", "-", "Noun"),
                  Word("Underground train", "U-Bahn", "die", "-en", "Noun"),
                  Word("transportation", "Verkehrsmittel", "das", "-", "Noun"),
                  Word("train", "Zug", "der", "-e", "Noun"),
                  Word("to depart", "abfahren", "ist", "abgefahren", "Verb"),
                  Word("to pick up", "abholen", "hat", "abgeholt", "Verb"),
                  Word("to arrive", "ankommen", "ist", "angekommen", "Verb"),
                  Word("to get off", "aussteigen", "ist", "ausgestiegen",
                      "Verb"),
                  Word(
                      "to get in", "einsteigen", "ist", "eingestiegen", "Verb"),
                  Word("to change trains", "umsteigen", "ist", "umgestiegen",
                      "Verb"),
                ],
                lessonColor: (Colors.red)!),
            Lesson(
                name: "Alltagsaktivitäten",
                words: [
                  Word("Work", "Arbeit", "die", "-en", "Noun"),
                  Word("Homework", "Hausaufgabe", "die", "-n", "Noun"),
                  Word("Pause", "Pause", "die", "-n", "Noun"),
                  Word("Newspaper", "Zeitung", "die", "-en", "Noun"),
                  Word("to cleanup", "aufräumen", "hat", "aufgeräumt", "Verb"),
                  Word("to invite", "einladen", "hat", "eingeladen", "Verb"),
                  Word("to buy", "kaufen", "hat", "gekauft", "Verb"),
                  Word("to laugh", "lachen", "hat", "gelacht", "Verb"),
                  Word("to learn", "lernen", "hat", "gelernt", "Verb"),
                  Word("to talk", "reden", "hat", "geredet", "Verb"),
                  Word("to sleep", "schlafen", "hat", "geschlafen", "Verb"),
                  Word("daily", "täglich", "*", "*", "Adjective"),
                ],
                lessonColor: (Colors.deepOrangeAccent[400])!),
            Lesson(
                name: "Jahreszeiten und Feste",
                words: [
                  Word("Spring", "Frühling", "der", "-e", "Noun"),
                  Word("Summer", "Sommer", "der", "-", "Noun"),
                  Word("Autumn", "Herbst", "der", "-e", "Noun"),
                  Word("Winter", "Winter", "der", "-", "Noun"),
                  Word("January", "Januar", "der", "-e", "Noun"),
                  Word("February", "Februar", "der", "-e", "Noun"),
                  Word("March", "März", "der", "-e", "Noun"),
                  Word("April", "April", "der", "-e", "Noun"),
                  Word("May", "Mai", "der", "-e", "Noun"),
                  Word("June", "Juni", "der", "-s", "Noun"),
                  Word("July", "Juli", "der", "-s", "Noun"),
                  Word("August", "August", "der", "-e", "Noun"),
                  Word("September", "September", "der", "-", "Noun"),
                  Word("October", "Oktober", "der", "-", "Noun"),
                  Word("November", "November", "der", "-", "Noun"),
                  Word("December", "Dezember", "der", "-", "Noun"),
                  Word("Festival", "Fest", "das", "-e", "Noun"),
                  Word("Wedding", "Hochzeit", "die", "-en", "Noun"),
                  Word("Carnival", "Karneval", "der", "-", "Noun"),
                  Word("New Year's Day", "Neujahr", "das", "-e", "Noun"),
                  Word("New Year's Eve", "Silvester", "das", "-", "Noun"),
                  Word("to start", "anfangen", "hat", "angefangen", "Verb"),
                  Word("to stop", "aufhören", "hat", "aufgehört", "Verb"),
                  Word("to celebrate", "feiern", "hat", "gefeiert", "Verb"),
                  Word("to last", "dauern", "hat", "gedauert", "Verb"),
                  Word("to like", "gefallen", "hat", "gefallen", "Verb"),
                ],
                lessonColor: (Colors.orange[900])!)
          ],
          color: (Colors.green[300])!),
      Level(
          name: "A2.1",
          lessons: [
            Lesson(
                name: "In der Stadt",
                words: [
                  Word("Stoplight", "Ampel", "die", "-n", "Noun"),
                  Word("Bank", "Bank", "die", "-en", "Noun"),
                  Word("Bridge", "Brücke", "die", "-n", "Noun"),
                  Word("Cathedral", "Dom", "der", "-e", "Noun"),
                  Word("Hotel", "Hotel", "das", "-s", "Noun"),
                  Word("City centre", "Stadtmitte", "die", "-n", "Noun"),
                  Word("City map", "Stadtplan", "der", "-e", "Noun"),
                  Word("Police", "Polizei", "die", "-en", "Noun"),
                  Word("Post", "Post", "die", "-en", "Noun"),
                  Word("Centre", "Zentrum", "das", "Zentren", "Noun"),
                  Word("Kilometer", "Kilometer", "der", "-", "Noun"),
                  Word("Meter", "Meter", "der", "-", "Noun"),
                  Word("Nearby", "Nähe", "die", "-", "Noun"),
                  Word("Way", "Weg", "der", "-e", "Noun"),
                  Word("to turn", "abbiegen", "ist", "abgebogen", "Verb"),
                  Word("to describe", "beschreiben", "hat", "beschrieben",
                      "Verb"),
                  Word("to continue", "weiterfahren", "ist", "weitergefahren",
                      "Verb"),
                  Word("to turn", "wenden", "hat", "gewendet", "Verb"),
                  Word("to drive back", "zurückfahren", "ist", "zurückgefahren",
                      "Verb"),
                  Word("foreign", "fremd", "*", "*", "Adjective"),
                  Word("left", "links", "*", "*", "Adjective"),
                  Word("right", "rechts", "*", "*", "Adjective"),
                ],
                lessonColor: Colors.amber),
            Lesson(
                name: "Wohnung",
                words: [
                  Word("House", "Haus", "das", "-er", "Noun"),
                  Word("Apartment", "Wohnung", "die", "-en", "Noun"),
                  Word("Balcony", "Balkon", "der", "-e", "Noun"),
                  Word("Tree", "Baum", "der", "Baüme", "Noun"),
                  Word("Flower", "Blume", "die", "-n", "Noun"),
                  Word("Ground floor", "Erdgeschoss", "das", "-e", "Noun"),
                  Word("Window", "Fenster", "das", "-", "Noun"),
                  Word("Garage", "Garage", "die", "-n", "Noun"),
                  Word("Garden", "Garten", "der", "Gärten", "Noun"),
                  Word("Basement", "Keller", "der", "-", "Noun"),
                  Word("Light", "Licht", "das", "-er", "Noun"),
                  Word("Rent", "Miete", "die", "-n", "Noun"),
                  Word("Garbage", "Müll", "der", "-", "Noun"),
                  Word("Neighbor", "Nachbar", "der", "-n", "Noun"),
                  Word("Square metre", "Quadratmeter", "der", "-", "Noun"),
                  Word("Floor", "Stock", "der", "-s", "Noun"),
                  Word("Staircase", "Treppe", "die", "-n", "Noun"),
                  Word("Landlord", "Vermieter", "der", "-", "Noun"),
                  Word("Water", "Wasser", "das", "-", "Noun"),
                  Word("Rent", "vermieten", "hat", "vermietet", "Verb"),
                  Word("comfortable", "gemütlich", "*", "*", "Adjective"),
                  Word("empty", "leer", "*", "*", "Adjective"),
                  Word("furnished", "mübliert", "*", "*", "Adjective"),
                  Word("Office", "Arbeitszimmer", "das", "-", "Noun"),
                  Word("Bathroom", "Bad", "das", "Bäder", "Noun"),
                  Word("Kitchen", "Küche", "die", "-n", "Noun"),
                  Word("Hallway", "Flur", "der", "-e", "Noun"),
                  Word("Children's room", "Kinderzimmer", "das", "-", "Noun"),
                  Word("Bedroom", "Schlafzimmer", "das", "-", "Noun"),
                  Word("Toilet", "Toilette", "die", "-n", "Noun"),
                  Word("Living room", "Wohnzimmer", "das", "-", "Noun"),
                  Word("Room", "Zimmer", "das", "-", "Noun"),
                  Word("Mountain", "Berg", "der", "-e", "Noun"),
                  Word("River", "Fluss", "der", "Flüsse", "Noun"),
                  Word("The sea", "Meer", "das", "-e", "Noun"),
                  Word("Forest", "Wald", "der", "Wälder", "Noun"),
                ],
                lessonColor: Colors.orange),
            Lesson(
                name: "Möbel",
                words: [
                  Word("Furniture", "Möbel", "die", "(Pl.)", "Noun"),
                  Word("Bed.", "Bett", "das", "-en", "Noun"),
                  Word("Image", "Bild", "das", "-er", "Noun"),
                  Word("Lamp", "Lampe", "die", "-n", "Noun"),
                  Word("Cabinet", "Schrank", "der", "-..e", "Noun"),
                  Word("Box", "Kasten", "der", "-", "Noun"),
                  Word("Armchair", "Sessel", "der", "-", "Noun"),
                  Word("Sofa", "das", "-s", "Sofa", "Noun"),
                  Word("Couch", "Couch", "die", "-(e)s/-en", "Noun"),
                  Word("Chair", "stuhl", "der", "-..e", "Verb"),
                  Word("carpet", "Teppich", "der", "-e", "Noun"),
                  Word("Table", "Tisch", "der", "-e", "Noun"),
                  Word("Euro", "Euro", "der", "-s", "Noun"),
                  Word("Cent", "Cent", "der", "-s", "Noun"),
                  Word("Price", "Preis", "der", "-e", "Noun"),
                  Word("Offer", "Angebot", "das", "-e", "Noun"),
                  Word("Help", "Hilfe", "die", "-n", "Noun"),
                  Word("Zimmer", "das", "", "Room", "Noun"),
                  Word("big", "groß", "-", "-", "erb"),
                  Word("ugly", "hässlich", "-", "-", "Ver"),
                  Word("small", "klein", "-", "-", "Vrb"),
                  Word("short", "kurz", "-", "-", "Vrb"),
                  Word("long", "lang", "-", "-", "Vrb"),
                  Word("light", "leicht", "-", "-", "Ver"),
                  Word("modern", "modern", "-", "-", "Veb"),
                  Word("convenient", "praktisch", "-", "-", "Veb"),
                  Word("bad", "schlecht", "-", "-", "Vrb"),
                  Word("nice", "schön", "-", "-", "Vrb"),
                  Word("heavy", "schwer", "-", "-", "Veb"),
                  Word("cheap", "günstig", "-", "-", "Vrb"),
                  Word("expensive", "teuer", "-", "-", "Vrb"),
                ],
                lessonColor: (Colors.lime[700])!),
            Lesson(
                name: "Farbe",
                words: [
                  Word("Colour", "Farbe", "die", "-n", "Noun"),
                  Word("blue", "blau", "*", "*", "Adjective"),
                  Word("brown", "braun", "*", "*", "Adjective"),
                  Word("yellow", "gelb", "*", "*", "Adjective"),
                  Word("green", "grün", "*", "*", "Adjective"),
                  Word("orange", "orange", "*", "*", "Adjective"),
                  Word("red", "rot", "*", "*", "Adjective"),
                  Word("black", "schwarz", "*", "*", "Adjective"),
                  Word("white", "weiß", "*", "*", "Adjective"),
                  Word("Shape", "Form", "die", "-en", "Noun"),
                  Word("rectangular", "eckig", "*", "*", "Adjective"),
                  Word("light", "leicht", "*", "*", "Adjective"),
                  Word("new", "neu", "*", "*", "Adjective"),
                  Word("round", "rund", "*", "*", "Adjective"),
                  Word("en", "Material", "das", "-", "Material"),
                  Word("Glass", "Glas", "das", "-..er", "Noun"),
                  Word("wood", "Holz", "das", "-..er", "Noun"),
                  Word("Metal", "Metall", "das", "-e", "Noun"),
                  Word("Paper", "Papier", "das", "-e", "Noun"),
                  Word("Plastic", "Plastik", "das", "-en", "Noun"),
                  Word("Plastic", "Kunststoff", "der", "-e", "Noun"),
                ],
                lessonColor: (Colors.lightGreen[800])!),
            Lesson(
                name: "Gegenstände",
                words: [
                  Word("Pencil", "Bleistift", "der", "-e", "Noun"),
                  Word("Glasses", "Brille", "die", "-n", "Noun"),
                  Word("Book", "Buch", "das", "-..er", "Noun"),
                  Word("Lighter", "Feuerzeug", "das", "-e", "Noun"),
                  Word("Bottle", "Flasche", "die", "-n", "Noun"),
                  Word("Camera", "Fotoapparat", "der", "-e", "Noun"),
                  Word("Purse", "Geldbörse", "die", "-n", "Noun"),
                  Word("chain", "Kette", "die", "-n", "Noun"),
                  Word("ballpoint pen", "Kugelschreiber", "der", "-", "Noun"),
                  Word("Umbrella", "Regenschirm", "der", "-e", "Noun"),
                  Word("Ring", "Ring", "der", "-e", "Noun"),
                  Word("Key", "Schlüssel", "der", "-", "Noun"),
                  Word("Soap", "Seife", "die", "-n", "Noun"),
                  Word("Match", "Streichholz", "das", "-..er", "Noun"),
                  Word("Bag", "Tasche", "die", "-n", "Noun"),
                  Word("Watch", "Uhr", "die", "-en", "Noun"),
                ],
                lessonColor: (Colors.cyan[800])!),
            Lesson(
                name: "Büro",
                words: [
                  Word("Workplace", "Arbeitsplatz", "der", "-..e", "Noun"),
                  Word("Screen", "Bildschirm", "der", "-e", "Noun"),
                  Word("Stamps", "Briefmarke", "die", "-n", "Noun"),
                  Word("Office", "Büro", "das", "-s", "Noun"),
                  Word("Boss", "Chef", "der", "-s", "Noun"),
                  Word("Computer", "Computer", "der", "-", "Noun"),
                  Word("Printer", "Drucker", "der", "-", "Noun"),
                  Word("Company", "Firma", "die", "-en", "Noun"),
                  Word("Formular", "Formular", "das", "-e", "Noun"),
                  Word("Mobile phone", "Handy", "das", "-s", "Noun"),
                  Word("Calendar", "Kalender", "der", "-", "Noun"),
                  Word("Laptop", "Laptop", "der", "-s", "Noun"),
                  Word("Mouse", "Maus", "die", "-..e", "Noun"),
                  Word("Notebook", "Notizbuch", "das", "-..er", "Noun"),
                  Word("bill", "Rechnung", "die", "-en", "Noun"),
                  Word("SMS", "SMS", "die", "-", "Noun"),
                  Word("pen", "Stift", "der", "-e", "Noun"),
                  Word("Meeting", "Termin", "der", "-e", "Noun"),
                ],
                lessonColor: (Colors.blue[900])!),
            Lesson(
                name: "Freizeit und Hobbys",
                words: [
                  Word("Excursion", "Ausflug", "der", "-e", "Noun"),
                  Word("Film", "Film", "der", "-e", "Noun"),
                  Word("Free time", "Freizeit", "die", "-", "Noun"),
                  Word("Hobby", "Hobby", "das", "-s", "Noun"),
                  Word("Cinema", "Kino", "das", "-s", "Noun"),
                  Word("Music", "Musik", "die", "-", "Noun"),
                  Word("Favourite film", "Lieblingsfilm", "der", "-e", "Noun"),
                  Word("to bake", "backen", "hat", "gebacken", "Verb"),
                  Word("to visit", "besuchen", "hat", "besucht", "Verb"),
                  Word("to meet", "treffen", "hat", "getroffen", "Verb"),
                  Word("to photograph", "fotografieren", "hat", "fotografiert",
                      "Verb"),
                  Word("to cook", "kochen", "hat", "gekocht", "Verb"),
                  Word("to read", "lesen", "hat", "gelesen", "Verb"),
                  Word("to love", "lieben", "hat", "geliebt", "Verb"),
                  Word("to paint", "malen", "hat", "gemalt", "Verb"),
                  Word("to hear music", "Musik hören", "hat", "gehört", "Verb"),
                  Word("to ride a bicycle", "Rad fahren", "ist", "gefahren",
                      "Verb"),
                  Word("to swim", "schwimmen", "ist", "geschwommen", "Verb"),
                  Word("to sing", "singen", "hat", "gesungen", "Verb"),
                  Word("to go for a walk", "Spazieren gehen", "ist", "gegangen",
                      "Verb"),
                  Word("to play", "spielen", "hat", "gespielt", "Verb"),
                  Word("to dance", "tanzen", "hat", "getanzt", "Verb"),
                ],
                lessonColor: (Colors.purple[700])!),
            Lesson(
                name: "In der Stadt",
                words: [
                  Word("Exhibition", "Ausstellung", "die", "-en", "Noun"),
                  Word("", "Bar", "die", "-s", "Bar"),
                  Word("Café", "Café", "das", "-s", "Noun"),
                  Word("Disco", "Disco", "die", "-s", "Noun"),
                  Word("Pub", "Kneipe", "die", "-n", "Noun"),
                  Word("Concert", "Konzert", "das", "-e", "Noun"),
                  Word("Museum", "Museum", "das", "Museen", "Noun"),
                  Word("Restaurant", "Restaurant", "das", "-s", "Noun"),
                  Word("Pool", "Schwimmbad", "das", "-..er", "Noun"),
                  Word("Theatre", "Theater", "das", "-", "Noun"),
                  Word("Tomorrow", "Morgen", "der", "-", "Noun"),
                  Word("Late Morning", "Vormittag", "der", "-e", "Noun"),
                  Word("Noon", "Mittag", "der", "-e", "Noun"),
                  Word("Afternoon", "Nachmittag", "der", "-e", "Noun"),
                  Word("Evening", "Abend", "der", "-e", "Noun"),
                  Word("Night", "Nacht", "die", "-..e", "Noun"),
                  Word("Day", "Tag", "der", "-e", "Noun"),
                  Word("Week", "Woche", "die", "-n", "Noun"),
                  Word("Monday", "Montag", "der", "-e", "Noun"),
                  Word("Tuesday", "Dienstag", "der", "-e", "Noun"),
                  Word("Wednesday", "Mittwoch", "der", "-e", "Noun"),
                  Word("Thursday", "Donnerstag", "der", "-e", "Noun"),
                  Word("Friday", "Freitag", "der", "-e", "Noun"),
                  Word("Saturday", "Samstag", "der", "-e", "Noun"),
                  Word("Sunday", "Sonntag", "der", "-e", "Noun"),
                ],
                lessonColor: (Colors.pink[900])!),
            Lesson(
                name: "Lebensmittel und Essen",
                words: [
                  Word("Apple", "Apfel", "der", "-..", "Noun"),
                  Word("Roast", "Braten", "der", "-", "Noun"),
                  Word("Buns", "Brötchen", "das", "-", "Noun"),
                  Word("Bread", "Brot", "das", "-e", "Noun"),
                  Word("Butter", "Butter", "die", "-", "Noun"),
                  Word("Egg", "Ei", "das", "-er", "Noun"),
                  Word("Ice cream", "Eis", "das", "-", "Noun"),
                  Word("Fish", "Fisch", "der", "-e", "Noun"),
                  Word("meat", "Fleisch", "das", "-", "Noun"),
                  Word("cheese", "Käse", "der", "-", "Noun"),
                  Word("Potato", "Kartoffel", "die", "-n", "Noun"),
                  Word("Cake", "Kuchen", "der", "-", "Noun"),
                  Word("Milk", "Milch", "die", "-", "Noun"),
                  Word("Fruit", "Obst", "das", "-", "Noun"),
                  Word("Orange", "Orange", "die", "-n", "Noun"),
                  Word("Rice", "Reis", "der", "-", "Noun"),
                  Word("Cream", "Sahne", "die", "-", "Noun"),
                  Word("Salad", "Salat", "der", "-e", "Noun"),
                  Word("Ham", "Schinken", "der", "-", "Noun"),
                  Word("Chocolate", "Schokolade", "die", "-n", "Noun"),
                  Word("Soup", "Suppe", "die", "-n", "Noun"),
                  Word("Tea", "Tee", "der", "-s", "Noun"),
                  Word("Tomato", "Tomate", "die", "-n", "Noun"),
                  Word("Sausage", "Wurst", "die", "-e", "Noun"),
                  Word("Lemon", "Zitrone", "die", "-n", "Noun"),
                  Word("Onion", "Zwiebel", "die", "-n", "Noun"),
                  Word("Thirst", "Durst", "der", "-", "Noun"),
                  Word("Breakfast", "Frühstück", "das", "-e", "Noun"),
                  Word("Hunger", "Hunger", "der", "-", "Noun"),
                  Word("Refrigerator", "Kühlschrank", "der", "-..e", "Noun"),
                  Word("to eat", "essen", "hat", "gegessen", "Verb"),
                  Word("to eat breakfast", "frühstücken", "hat", "gefrühstückt",
                      "Verb"),
                  Word("to like", "mägen", "hat", "gemocht", "Verb"),
                  Word("to taste", "schmecken", "hat", "geschmekt", "Verb"),
                  Word("to drink", "trinken", "hat", "getrunken", "Verb"),
                ],
                lessonColor: Colors.pink),
            Lesson(
                name: "Verkehrsmittel und Reisen",
                words: [
                  Word("Train station", "Bahnhof", "der", "-e", "Noun"),
                  Word("Platform", "Bahnsteig", "der", "-e", "Noun"),
                  Word("Bus", "Bus", "der", "-se", "Noun"),
                  Word("Stop", "Haltestelle", "die", "-n", "Noun"),
                  Word("Airport", "Flughafen", "der", "-..", "Noun"),
                  Word("Plane", "Flugzeug", "das", "-e", "Noun"),
                  Word("Luggage", "Gepäck", "das", "-", "Noun"),
                  Word("Track", "Gleis", "das", "-e", "Noun"),
                  Word("Suitcase", "Koffer", "der", "-", "Noun"),
                  Word("Suburban train", "S-Bahn", "die", "-en", "Noun"),
                  Word("Tram", "Straßenbahn", "die", "-", "Noun"),
                  Word("Underground train", "U-Bahn", "die", "-en", "Noun"),
                  Word("transportation", "Verkehrsmittel", "das", "-", "Noun"),
                  Word("train", "Zug", "der", "-e", "Noun"),
                  Word("to depart", "abfahren", "ist", "abgefahren", "Verb"),
                  Word("to pick up", "abholen", "hat", "abgeholt", "Verb"),
                  Word("to arrive", "ankommen", "ist", "angekommen", "Verb"),
                  Word("to get off", "aussteigen", "ist", "ausgestiegen",
                      "Verb"),
                  Word(
                      "to get in", "einsteigen", "ist", "eingestiegen", "Verb"),
                  Word("to change trains", "umsteigen", "ist", "umgestiegen",
                      "Verb"),
                ],
                lessonColor: (Colors.red)!),
            Lesson(
                name: "Alltagsaktivitäten",
                words: [
                  Word("Work", "Arbeit", "die", "-en", "Noun"),
                  Word("Homework", "Hausaufgabe", "die", "-n", "Noun"),
                  Word("Pause", "Pause", "die", "-n", "Noun"),
                  Word("Newspaper", "Zeitung", "die", "-en", "Noun"),
                  Word("to cleanup", "aufräumen", "hat", "aufgeräumt", "Verb"),
                  Word("to invite", "einladen", "hat", "eingeladen", "Verb"),
                  Word("to buy", "kaufen", "hat", "gekauft", "Verb"),
                  Word("to laugh", "lachen", "hat", "gelacht", "Verb"),
                  Word("to learn", "lernen", "hat", "gelernt", "Verb"),
                  Word("to talk", "reden", "hat", "geredet", "Verb"),
                  Word("to sleep", "schlafen", "hat", "geschlafen", "Verb"),
                  Word("daily", "täglich", "*", "*", "Adjective"),
                ],
                lessonColor: (Colors.deepOrangeAccent[400])!),
            Lesson(
                name: "Jahreszeiten und Feste",
                words: [
                  Word("Spring", "Frühling", "der", "-e", "Noun"),
                  Word("Summer", "Sommer", "der", "-", "Noun"),
                  Word("Autumn", "Herbst", "der", "-e", "Noun"),
                  Word("Winter", "Winter", "der", "-", "Noun"),
                  Word("January", "Januar", "der", "-e", "Noun"),
                  Word("February", "Februar", "der", "-e", "Noun"),
                  Word("March", "März", "der", "-e", "Noun"),
                  Word("April", "April", "der", "-e", "Noun"),
                  Word("May", "Mai", "der", "-e", "Noun"),
                  Word("June", "Juni", "der", "-s", "Noun"),
                  Word("July", "Juli", "der", "-s", "Noun"),
                  Word("August", "August", "der", "-e", "Noun"),
                  Word("September", "September", "der", "-", "Noun"),
                  Word("October", "Oktober", "der", "-", "Noun"),
                  Word("November", "November", "der", "-", "Noun"),
                  Word("December", "Dezember", "der", "-", "Noun"),
                  Word("Festival", "Fest", "das", "-e", "Noun"),
                  Word("Wedding", "Hochzeit", "die", "-en", "Noun"),
                  Word("Carnival", "Karneval", "der", "-", "Noun"),
                  Word("New Year's Day", "Neujahr", "das", "-e", "Noun"),
                  Word("New Year's Eve", "Silvester", "das", "-", "Noun"),
                  Word("to start", "anfangen", "hat", "angefangen", "Verb"),
                  Word("to stop", "aufhören", "hat", "aufgehört", "Verb"),
                  Word("to celebrate", "feiern", "hat", "gefeiert", "Verb"),
                  Word("to last", "dauern", "hat", "gedauert", "Verb"),
                  Word("to like", "gefallen", "hat", "gefallen", "Verb"),
                ],
                lessonColor: (Colors.orange[900])!)
          ],
          color: (Colors.green[300])!),
      Level(
          name: "A2.2",
          lessons: [
            Lesson(
                name: "Lerntipps",
                words: [
                  Word("Task", "Aufgabe", "die", "-n", "Noun"),
                  Word("Goethe Institute", "Goethe-Institut", "das", "-e",
                      "Noun"),
                  Word("Class", "Klasse", "die", "-n", "Noun"),
                  Word("News", "Nachricht", "die", "-en", "Noun"),
                  Word("Term", "Semester", "das", "-", "Noun"),
                  Word(
                      "Language school", "Sprachenschule", "die", "-n", "Noun"),
                  Word("Test", "Test", "der", "-s", "Noun"),
                  Word("Type", "Typ", "der", "-en", "Noun"),
                  Word("Community school", "Volkshochschule", "die", "-n",
                      "Noun"),
                  Word("to write down", "aufschreiben", "hat", "aufgeschrieben",
                      "Verb"),
                  Word("to move", "bewegen (sich)", "hat", "sich bewegt",
                      "Verb"),
                  Word(
                      "to correct", "korrigieren", "hat", "korrigiert", "Verb"),
                  Word("to solve", "lösen", "hat", "gelöst", "Verb"),
                  Word("to notice", "merken (sich)", "hat sich", "gemerkt",
                      "Verb"),
                  Word(
                      "to translate", "übersetzen", "hat", "übersetzt", "Verb"),
                  Word("to repeat", "wiederholen", "hat", "wiederholt", "Verb"),
                  Word("Present", "Gegenwart", "die", "-", "Noun"),
                  Word("Past", "Vergangenheit", "die", "-", "Noun"),
                  Word("to plan", "planen", "hat", "geplant", "Verb"),
                  Word("to fall in love", "verlieben (sich)", "hat",
                      " sich verliebt", "Verb"),
                  Word("to travel", "verreisen", "ist", "verreist", "Verb"),
                  Word("possible", "möglich", "-", "-", "Adjective"),
                  Word("Made by", "Gharbi", "Anas", "", "Noun"),
                ],
                lessonColor: (Colors.amber)),
            Lesson(
                name: "Post",
                words: [
                  Word("Sender", "Absender", "der", "-", "Noun"),
                  Word("Boy", "Junge", "der", "-n", "Noun"),
                  Word("Letter box", "Briefkasten", "der", "-..", "Noun"),
                  Word("Receiver", "Empfänger", "der", "-", "Noun"),
                  Word("Packet", "Päckchen", "das", "-", "Noun"),
                  Word("Project", "Projekt", "das", "-e", "Noun"),
                  Word("Step", "Schritt", "der", "-e", "Noun"),
                  Word("Table", "Tafel", "die", "-n", "Noun"),
                  Word("Package", "Paket", "das", "-e", "Noun"),
                  Word("Centimetre", "Zentimeter", "der", "-", "Noun"),
                  Word("Counter", "Schalter", "der", "-", "Noun"),
                  Word("Signature", "Unterschrift", "die", "-en", "Noun"),
                  Word("Instructions for use", "Gebrauchsanweisung", "die",
                      "-en", "Noun"),
                  Word("to mark", "ankreuzen", "hat", "angekreuzt", "Verb"),
                  Word("to pack in", "einpacken", "hat", "eingepackt", "Verb"),
                  Word("to use", "benutzen", "hat", "benutzt", "Verb"),
                  Word("to pack", "packen", "hat", "gepackt", "Verb"),
                  Word("to think of", "denken an", "hat", "an...gedacht",
                      "Verb"),
                  Word("to transport", "transportieren", "hat", "transportiert",
                      "Verb"),
                  Word("to add", "ergänzen", "hat", "ergänzt", "Verb"),
                  Word("to sign", "unterschreiben", "hat", "unterschrieben",
                      "Verb"),
                  Word("to use (need)", "gebrauchen", "hat", "gebraucht",
                      "Verb"),
                  Word("to need ", "brauchen", "hat", "gebraucht", "Verb"),
                  Word("Made by", "Gharbi", "Anas", "", "Noun"),
                ],
                lessonColor: (Colors.amber[300])!),
            Lesson(
                name: "Medien",
                words: [
                  Word("DVD", "DVD", "die", "-s", "Noun"),
                  Word("TV", "Fernsehen", "das", "-", "Noun"),
                  Word("Episode", "Folge", "die", "-n", "Noun"),
                  Word("murder mystery", "Krimi", "der", "-s", "Noun"),
                  Word("Schedule", "Programm", "das", "-e", "Noun"),
                  Word("Broadcast", "Rundfunk", "der", "-", "Noun"),
                  Word("Channel", "Sender", "der", "-", "Noun"),
                  Word("Private channel", "Privatsender", "der", "-", "Noun"),
                  Word("Show", "Sendung", "die", "-en", "Noun"),
                  Word("Series", "Serie", "die", "-n", "Noun"),
                  Word("Feature film", "Spielfilm", "der", "-e", "Noun"),
                  Word("Video", "Video", "das", "-s", "Noun"),
                  Word("Audience", "Zuschauer", "der", "-", "Noun"),
                  Word("public", "öffentlich", "-", "-", "Adjective"),
                  Word("Restaurant/Bar", "Gaststätte", "die", "-n", "Noun"),
                  Word("Guesthouse", "Gasthaus", "das", "-er", "Noun"),
                  Word("Area", "Gegend", "die", "-en", "Noun"),
                  Word("to look/peep ", "gucken", "hat", "geguckt", "Verb"),
                  Word("to look", "schauen", "hat", "geschaut", "Verb"),
                  Word(
                      "to produce", "produzieren", "hat", "produziert", "Verb"),
                  Word("private", "privat", "-", "-", "Adjective"),
                  Word("to mean", "bedeuten", "hat", "bedeutet", "Verb"),
                  Word("Habit", "Gewohnheit", "die", "-en", "Noun"),
                  Word("almost/just", "knapp", "-", "-", "Adverb"),
                  Word("fixed", "fest", "-", "-", "Adjective"),
                  Word("social", "sozial", "-", "-", "Adjective"),
                  Word("except", "außer", "-", "-", "Adverb"),
                  Word("meanwhile", "inzwischen", "-", "-", "Adverb"),
                  Word("Made by", "Gharbi", "Anas", "", "Noun"),
                ],
                lessonColor: Colors.orange),
          ],
          color: (Colors.blue[800])!),
    ];
  }
}
